query customerData {
  customer {
    firstName
    entityId
    attributes {
      productBulkOrderList: attribute(entityId: 1) {
        entityId
        value
        name
      }
      showPage: attribute(entityId: 2) {
        entityId
        value
        name
      }
    }
  }
}
