query CustomBrand(
    $cursor: String,
) {
    site {
        brands(first: 2, after:$cursor) {
            pageInfo {
                endCursor
                hasNextPage
            },
            edges {
                node {
                id
                entityId
                name
                defaultImage {
                    url(width: 100)
                }
                path
                }
            }
        }
    }
}