query getProductsSku(
    $sku: String,
) {
    site {
      product(sku: $sku) {
        id
        entityId
        name
        sku
        description
        plainTextDescription
      	inventory{
          aggregated{
            availableToSell
          }
        }
        prices {
            price {
                currencyCode
                value
            }
        }
        defaultImage {
          url(width: 100)
        }
        variants{
                  edges{
                    node{
                      id
                      entityId
                      sku
                      productOptions{
                        edges{
                          node {
                            entityId
                            displayName
                            isRequired
                            ... on CheckboxOption {
                                checkedByDefault
                            }
                          }
                      }
                    }
                 }
              }
          }
      }
    }
}